<?php 

/***************************************************************************/
/*
/* 	----------------------------------------------------------------------
/* 						DO NOT EDIT THIS FILE
/*	----------------------------------------------------------------------
/* 
/*  			Built by Darcy Clarke. http://themify.me
/*  				Copyright (C) 2010 Themify
/*
/***************************************************************************/

require_once(TEMPLATEPATH . '/themify/themify-database.php');
require_once(TEMPLATEPATH . '/themify/themify-utils.php');
require_once(TEMPLATEPATH . '/themify/themify-config.php');
require_once(TEMPLATEPATH . '/themify/themify-modules.php');
require_once(TEMPLATEPATH . '/theme-modules.php');
require_once(TEMPLATEPATH . '/theme-functions.php');

if(is_file(TEMPLATEPATH . '/custom-modules.php')){
	require_once(TEMPLATEPATH . '/custom-modules.php');
}

if(is_file(TEMPLATEPATH . '/custom-functions.php')){
	require_once(TEMPLATEPATH . '/custom-functions.php');
}

require_once(TEMPLATEPATH . '/themify/themify-widgets.php');

/***********************************************************************************************************
 * 
 * Do not edit this file.
 * To add custom PHP functions to the theme, create a new 'custom-functions.php' file in the theme folder.
 * 
************************************************************************************************************/

?>