<?php
/**
 * @package themify
 * @since 1.1.5
 * @author Elio Rivero
 * 
 * ----------------------------------------------------------------------
 * 					DO NOT EDIT THIS FILE
 * ----------------------------------------------------------------------
 * 				Themify Shortcodes
 *  			http://themify.me
 *  			Copyright (C) 2012 Themify
 *
 * Hooks:
 * 		themify_body_start
 * 
 * 		themify_header_before
 * 		themify_header_start
 * 		themify_header_end
 * 		themify_header_after
 * 
 * 		themify_layout_before
 * 
 * 		themify_content_before 
 * 		themify_content_start
 * 
 * 		themify_post_before
 * 		themify_post_start
 *		themify_post_end
 * 		themify_post_after
 * 
 * 		themify_comment_before
 * 		themify_comment_start
 * 		themify_commentform_before
 * 		themify_commentform_start
 * 		themify_commentform_end
 * 		themify_commentform_after
 * 		themify_comment_end
 * 		themify_comment_after
 * 
 *		themify_content_end
 * 		themify_content_after
 * 
 * 		themify_sidebar_before
 * 		themify_sidebar_start
 * 		themify_sidebar_end
 * 		themify_sidebar_after
 * 
 * 		themify_layout_after
 * 
 * 		themify_footer_before
 * 		themify_footer_start
 * 		themify_footer_end
 *		themify_footer_after
 * 
 *		themify_body_end
 * 
***************************************************************************/

function themify_body_start() { 		do_action( 'themify_body_start' ); }

function themify_header_before() { 		do_action( 'themify_header_before' ); }
function themify_header_start() { 		do_action( 'themify_header_start' ); }
function themify_header_end() { 		do_action( 'themify_header_end' ); }
function themify_header_after(){ 		do_action( 'themify_header_after'); }

function themify_layout_before() { 		do_action( 'themify_layout_before' ); }

function themify_content_before (){		do_action('themify_content_before '); }
function themify_content_start(){ 		do_action('themify_content_start'); }

function themify_post_before(){ 		do_action('themify_post_before'); }
function themify_post_start() { 		do_action( 'themify_post_start' ); }
function themify_post_end() { 			do_action( 'themify_post_end' ); }
function themify_post_after() { 		do_action( 'themify_post_after' ); }

function themify_comment_before() { 	do_action( 'themify_comment_before' ); }
function themify_comment_start() { 		do_action( 'themify_comment_start' ); }
function themify_commentform_before(){ 	do_action( 'themify_commentform_before'); }
function themify_commentform_start (){	do_action('themify_commentform_start '); }
function themify_commentform_end(){ 	do_action('themify_commentform_end'); }
function themify_commentform_after(){ 	do_action('themify_commentform_after'); }
function themify_comment_end() { 		do_action( 'themify_comment_end' ); }
function themify_comment_after() { 		do_action( 'themify_comment_after' ); }

function themify_content_end() { 		do_action( 'themify_content_end' ); }
function themify_content_after() { 		do_action( 'themify_content_after' ); }

function themify_sidebar_before(){ 		do_action( 'themify_sidebar_before'); }
function themify_sidebar_start (){		do_action('themify_sidebar_start '); }
function themify_sidebar_end(){ 		do_action('themify_sidebar_end'); }
function themify_sidebar_after(){ 		do_action('themify_sidebar_after'); }

function themify_layout_after() { 		do_action( 'themify_layout_after' ); }

function themify_footer_before() { 		do_action( 'themify_footer_before' ); }
function themify_footer_start() { 		do_action( 'themify_footer_start' ); }
function themify_footer_end() { 		do_action( 'themify_footer_end' ); }
function themify_footer_after() { 		do_action( 'themify_footer_after' ); }

function themify_body_end() { 			do_action( 'themify_body_end' ); }

?>