<?php

/***************************************************************************/
/* 
/* 	----------------------------------------------------------------------
/* 						DO NOT EDIT THIS FILE
/*	----------------------------------------------------------------------
/* 
/*  			Built by Darcy Clarke. http://themify.me
/*  				Copyright (C) 2010 Themify
/*
/***************************************************************************/

/* 	AJAX
/***************************************************************************/
	
	error_reporting(0);
	
	$script = $_SERVER['SCRIPT_FILENAME'];
	$wppos = stripos($_SERVER['SCRIPT_FILENAME'],"wp-content");
	$finalstr = substr($_SERVER['SCRIPT_FILENAME'],0,$wppos);
	require_once($finalstr.'wp-load.php');
	require_once($finalstr.'wp-includes/wp-db.php');
	require_once('themify-utils.php');
	require_once('themify-config.php');
	
	///////////////////////////////////////////
	// Grab Settings
	///////////////////////////////////////////
	function themify_pull(){
		print_r(get_data());		
	}
	if($_GET['pull']){
		themify_pull();
	}
	add_action('wp_ajax_themify_pull', 'themify_pull');
	
	///////////////////////////////////////////
	// Import
	///////////////////////////////////////////
	function themify_import(){
		if(!empty($_FILES)) {
			if(!is_dir(TEMPLATEPATH.'/themify/temp')){		
				mkdir(TEMPLATEPATH.'/themify/temp', 0777);
			}
			if(move_uploaded_file($_FILES['Filedata']['tmp_name'], TEMPLATEPATH.'/themify/temp/'.basename($_FILES['Filedata']['name']))){
				$file = basename($_FILES['Filedata']['name']);
				$ext = substr(strrchr($file, '.'), 1);
				$dir = "temp/";
				if($ext == 'zip' || $ext == 'rar'){
					themify_extract_zip(TEMPLATEPATH.'/themify/'.$dir.$file);
				} else if($ext == 'txt'){
					$handler = fopen($dir.$file, 'r');
					if(filesize($dir.$file) > 0){
						$data = fread($handler, filesize($dir.$file));
						set_data(unserialize($data));
					}
					fclose($fh);	
				}
				$handle = opendir("temp/");
   				while($file = readdir($handle)){
      				if($file != "." && $file != ".."){
            			unlink("temp/".$file);
					}
				}
				rmdir("temp/");
				echo "true";
			} else {
				echo "false";
			}
		}	
	}
	if($_GET['import']){
		themify_import();
	}
	add_action('wp_ajax_themify_import', 'themify_import');
	
	///////////////////////////////////////////
	// Extract
	///////////////////////////////////////////
	function themify_export(){
		global $theme;
		$datafile = "data_export.txt";
		$handler = fopen($datafile, 'w');
		if(class_exists('ZipArchive') && $handler != false){
			fwrite($handler,serialize(get_data()));
			fclose($handler);
			$files_to_zip = array(
				'../config.xml',
				'../custom_modules.php',
				'../custom_widgets.php',
				$datafile
			);
			$file = $theme['Name'].'_themify_export_'.date("Y-m-d").'.zip';
			$result = themify_create_zip($files_to_zip, $file, true);
			if($result){
				themify_force_download($file);
				unlink($datafile);
				unlink($file);
			}
		} else {
			if(ini_get('zlib.output_compression')) { 
				ini_set('zlib.output_compression', 'Off');	
			}
			header('Pragma: public');
			header('Expires: 0');
			header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
			header('Cache-Control: private',false);
			header('Content-Type: application/force-download');
			header('Content-Disposition: attachment; filename="'.$theme['Name'].'_themify_export_'.date("Y-m-d").'.txt"');
			header('Content-Transfer-Encoding: binary');
			echo serialize(get_data());
			exit();
		}
	}
	if($_GET['export']){
		themify_export();		
	}
	add_action('wp_ajax_themify_reset_setting', 'themify_reset_setting');
	
	///////////////////////////////////////////
	// Upload Image
	///////////////////////////////////////////
	function themify_upload(){
		if(!empty($_FILES)) {
			if(!isset($_POST['target']) || $_POST['target'] == ''){
				$target = TEMPLATEPATH.'/uploads/';
			} else {
				$target = TEMPLATEPATH.'/'.$_POST['target'];
			}	
			$target = rtrim($target, "/");
			$check = false;
			if(!is_dir($target)){		
				if(!mkdir($target, 0777, true)){
					echo "false";	
				} else {
					$check = true; 	
				}
			} else {
				$check = true;	
			}
			if($check){
				if(move_uploaded_file($_FILES['Filedata']['tmp_name'], $target."/".str_replace(" ", "-", basename($_FILES['Filedata']['name'])))){
					echo str_replace(" ", "-", basename($_FILES['Filedata']['name']));
				} else {
					echo "false";
				}
			}
		}
	}
	if($_GET['upload']){
		themify_upload();
	}
	add_action('wp_ajax_themify_upload', 'themify_upload');
	
	/**
	 * Upload Image - To Wordpress Uploads
	 * @since 1.1.5
	 */
	function themify_upload_wordpress(){
		if(!empty($_FILES)){
			//We need the post id of the current post to attach the image
			if(isset($_POST['postid']))	$postid = $_POST['postid'];
			else echo 'No post id.';
			
			/**
			 * Includes required files for
			 * 		media_handle_upload
			 * 		wp_handle_upload
			 * 		wp_generate_attachment_metadata
			 */
			require_once(ABSPATH . 'wp-admin/includes/file.php');
			require_once(ABSPATH . 'wp-admin/includes/media.php');
			require_once(ABSPATH . 'wp-admin/includes/image.php');
			
			//'Filedata' is the key used by Uploadify for $_FILES
			$attach_id = media_handle_upload( 'Filedata', $postid );
			
			//If something went wrong, media_handle_upload returns WP_Error
			if (is_wp_error( $upl_id )) {
	        	echo $upl_id->errors['upload_error']['0'];
		    }
		    else {
		    	//File was correctly uploaded and added to media library.
		    	$att = get_post($attach_id);
				//Return URL for the image field in meta box
				echo $att->guid;
				//Set the featured image for the post
				set_post_thumbnail($postid, $attach_id);
				update_post_meta($postid, $_POST['customfield'], $att->guid);
		    }
		}
		else {
			echo '$_FILES is empty';
		}
	}
	if($_GET['upload-wordpress']){
		themify_upload_wordpress();	
	}
	add_action('wp_ajax_themify_upload_wordpress', 'themify_upload_wordpress');
	
	///////////////////////////////////////////
	// Delete Image
	///////////////////////////////////////////
	function themify_delete_image(){
		if(file_exists("../".$_POST['file'])){
			unlink("../".$_POST['file']);
			echo "true";
		} else {
			echo "false";	
		}	
	}
	if($_GET['delete-image']){
		themify_delete_image();
	}
	add_action('wp_ajax_themify_delete_image', 'themify_delete_image');
	
?>